name: .NET Core build & build docker dev image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      run: sudo apt-get install -y mono-complete
    - name: Install dependencies
      run: nuget install -o packages
    - name: Build executable
      run: msbuild -p:Configuration=Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: NeoDocCompiled
        # A file, directory or wildcard pattern that describes what to upload
        path: bin/Release/*
        retention-days: 30
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.0.1
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # List of tags
        tags: docker.pkg.github.com/ttt-2/neodoc:dev
        # Always attempt to pull a newer version of the image
        pull: true
        load: true
    - name: Push docker image
      if: github.event_name != 'pull_request'
      run: docker push ghcr.io/ttt-2/neodoc:dev
