name: .NET Core build & build docker dev image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        run: sudo apt-get install -y mono-complete
      - name: Install dependencies
        run: nuget install -o packages
      - name: Build executable
        run: msbuild -p:Configuration=Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeoDocCompiled
          path: bin/Release/*
          retention-days: 30
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/ttt-2/neodoc/neodoc:dev
          pull: true
          push: true
          load: true
        if: github.event_name != 'pull_request'
