name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      run: sudo apt-get install -y mono-complete
    - name: Install dependencies
      run: msbuild restore
    - name: Build executable
      run: msbuild -p:Configuration=Release
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.0.1
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # List of tags
        tags: ghcr.io/TTT-2/neodoc:latest
        # Always attempt to pull a newer version of the image
        pull: true
        # Push is a shorthand for --output=type=registry
        push: ${{ github.event_name != 'pull_request' }}
