name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      run: apt-get install -y mono-complete
    - name: Install dependencies
      run: msbuild restore
    - name: Build
      run: msbuild -p:Configuration=Release
